[sdl]
fullscreen = false
fulldouble = false
fullresolution = desktop
windowresolution = original
output = opengl
autolock = false
middle_unlock = auto
usesystemcursor = true
mouse_emulation = auto
usescancodes = true
priority = normal,normal

[dosbox]
machine = svga_s3
memsize = 16
quit warning = false
resolve config path = true

[cpu]
cputype = 486_slow
cycles = auto
cyclemax = 60000

[mixer]
nosound = false
sample accurate = false
rate = 44100
blocksize = 1024
prebuffer = 25

[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
dma = 1
hdma = 5
enable speaker = true
sbmixer = true
oplmode = auto
oplemu = default

[speaker]
pcspeaker = true

[midi]
mpu401 = none
mididevice = none

[joystick]
joysticktype = none

[dos]
keyboardlayout = auto
lfn = auto
automount = false
automountall = false
startcmd = false

[config]
dos = high, umb

[autoexec]
