# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Peach 1UP, one-dir build.
# Prerequisites: build frontend (npm run build) and docs (npm run build) before running pyinstaller.

from pathlib import Path

from PyInstaller.utils.hooks import collect_submodules

# sandbox_host.exe ships prebuilt inside the pip-installed wincage wheel's
# package directory. PyInstaller's own import analysis does not pick up
# non-Python package data automatically, so it needs an explicit datas entry.
# Destination "wincage" mirrors the installed package layout, matching where
# build.bat's own copy step (dist\peach1up\wincage\) expects to find it.
import wincage  # noqa: E402

_SANDBOX_HOST_EXE = Path(wincage.__file__).parent / "sandbox_host.exe"
if not _SANDBOX_HOST_EXE.is_file():
    raise FileNotFoundError(
        f"sandbox_host.exe not found at {_SANDBOX_HOST_EXE}. "
        "The installed wincage wheel did not include a prebuilt binary."
    )

# magic_signatures.toml ships inside the pip-installed formatscout wheel's
# package directory and is opened relative to its own module file at import
# time (formatscout/magic/magic_detect.py), not through any Python import
# mechanism. PyInstaller's own import analysis does not pick up non-Python
# package data automatically, so it needs an explicit datas entry.
# Destination "formatscout/magic" mirrors the installed package layout so
# the same Path(__file__).parent lookup resolves in the frozen build.
import formatscout.magic  # noqa: E402

_MAGIC_SIGNATURES_TOML = Path(formatscout.magic.__file__).parent / "magic_signatures.toml"
if not _MAGIC_SIGNATURES_TOML.is_file():
    raise FileNotFoundError(
        f"magic_signatures.toml not found at {_MAGIC_SIGNATURES_TOML}. "
        "The installed formatscout wheel did not include its magic signature data."
    )

hiddenimports = (
    collect_submodules("fastapi")
    + collect_submodules("starlette")
    + collect_submodules("uvicorn")
    + collect_submodules("sqlmodel")
    + collect_submodules("pydantic")
    + [
        "pystray",
        "pystray._win32",
        "PIL",
        "PIL.Image",
        "sqlalchemy",
        "sqlalchemy.dialects.sqlite",
        "passlib",
        "passlib.handlers",
        "passlib.handlers.bcrypt",
        "passlib.handlers.argon2",
        "argon2",
        "pydantic_settings",
        "yaml",
        "pycdlib",
    ]
)

block_cipher = None

a = Analysis(
    ["peach1up_launcher.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("backend/", "backend/"),
        ("config/", "config/"),
        ("assets/", "assets/"),
        ("frontend/dist/", "frontend/dist/"),
        ("docs/build/", "docs/build/"),
        ("scripts/", "scripts/"),
        (str(_SANDBOX_HOST_EXE), "wincage"),
        (str(_MAGIC_SIGNATURES_TOML), "formatscout/magic"),
    ],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "test",
        "tests",
        "testing",
        "pytest",
        "setuptools",
        "distutils",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# User-supplied asset directories that must never be packaged. Matched as whole
# path components, never as substrings: a substring match here also dropped
# config/emulators/86box-roms.toml (the 86Box ROM-pack catalog entry, leaving
# the packaged build with no such emulator) and the built bios-sourcing docs
# page, because their names merely contain "roms" and "bios".
_USER_ASSET_DIRS = frozenset(("roms", "bios", "saves", "vms"))


def _in_user_asset_dir(dest):
    return bool(_USER_ASSET_DIRS.intersection(dest.replace("\\", "/").split("/")))


a.datas = [
    (dest, src, kind)
    for dest, src, kind in a.datas
    if "__pycache__" not in dest
    and not any(seg in dest for seg in ("test_", "_test.", "/tests/", "/test/"))
    and not _in_user_asset_dir(dest)
    and dest.replace("\\", "/") != "config/emulators.yaml"
    and dest.replace("\\", "/") not in (
        "scripts/manage_test_users.py",
        "scripts/run_tests.py",
    )
]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="peach1up",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # assets/peach1up.ico is generated by scripts/gen_icon.py alongside peach1up.png
    icon="assets/peach1up.ico",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="peach1up",
)