first_run_complete: true
DOSBOX_PATH: emulators/dosbox-x/dosbox-x.exe
BOX86_PATH: emulators/86box/86Box.exe
VIRTUALBOX_PATH: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
LIBRARY_PATH: library
MEDIA_PATH: library/media
OS_PATH: library/system/os
DRIVES_PATH: library/system/drives
ROMS_PATH: library/system/roms/86box
BIOS_PATH: library/system/bios
PROFILES_PATH: library/system/profiles
DUCKSTATION_PATH: C:/Users/ryanm/AppData/Local/Programs/DuckStation/duckstation-qt-x64-ReleaseLTCG.exe
PCSX2_PATH: emulators/pcsx2/pcsx2-qt.exe
XEMU_PATH: emulators/xemu/xemu.exe
MESEN_PATH: emulators/mesen/Mesen.exe
PROJECT64_PATH: C:/Program Files (x86)/Project64 3.0/Project64.exe
PS1_BIOS_PATH: ''
PS2_BIOS_PATH: ''
XBOX_BIOS_PATH: ''
DREAMCAST_BIOS_PATH: library/system/bios/dreamcast
suppress_confirmations: []
PEACH_ENV: development
SESSION_SECRET: 090dbf2838d695ecd63cfa196c9921109266e29cdbdd9b6751a6185c8ab2a784
