slug = "standard"
display_name = "Standard"
description = "Works for most software. Good 2D performance."
best_for = ["win95", "win98", "winxp"]
machine = "bf6"
cpu_family = "pentium2_deschutes"
cpu_speed = 300000000
cpu_multi = 3.5
cpu_use_dynarec = 1
fpu_type = "internal"
mem_size = 131072
gfxcard = "px_trio64vplus_pci"
vid_renderer = "qt_software"
sndcard = "sb16_pnp"
keyboard_type = "keyboard_ps2"
mouse_type = "ps2"
